version: '3.8'

services:
    postgresdb:
        container_name: postgres
        image: postgres:alpine3.20
        restart: unless-stopped
        env_file: ./.env
        environment:
            - POSTGRES_USER=$POSTGRESDB_USER
            - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
            - POSTGRES_DB=$POSTGRESDB_DATABASE
        ports:
            - ${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}
        volumes:
            - ${PC_DATABASE_PATH}:${CONTAINER_PATH}

    redisdb:
        container_name: redis:7.4-rc2-alpine3.20
        image: redis
        ports:
            - ${REDIS_LOCAL_PORT}:${REDIS_DOCKER_PORT}

    app:
        container_name: app
        depends_on:
            - postgresdb
        build:
            args:
                VERSION: 1.0.0
            context: .
            dockerfile: Dockerfile
        restart: on-failure
        env_file: ./.env
        ports:
            - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
        environment:
            SPRING_APPLICATION_JSON: '{
                "spring.datasource.driver-class-name": "org.postgresql.Driver",
                "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.PostgreSQLDialect",
                "spring.datasource.url": "jdbc:postgresql://postgresdb:$POSTGRESDB_DOCKER_PORT/$POSTGRESDB_DATABASE",
                "spring.datasource.username": "$POSTGRESDB_USER",
                "spring.datasource.password": "$POSTGRESDB_ROOT_PASSWORD",
                "spring.jpa.show-sql": "true",
                "spring.jpa.hibernate.ddl-auto": "update"
            }'
        stdin_open: true
        tty: true

volumes:
    it_services_pg_data: