version: '3.8'

services:
    postgresdb:
        container_name: postgres
        image: postgres:alpine3.20
        restart: unless-stopped
        env_file: ./.env
        environment:
            - POSTGRES_USER=$POSTGRESDB_USER
            - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
            - POSTGRES_DB=$POSTGRESDB_DATABASE
        ports:
            - ${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}
        volumes:
            - ${PC_DATABASE_PATH}:${CONTAINER_PATH}

    app:
        container_name: app
        depends_on:
            - postgresdb
        build:
            context: .
            dockerfile: Dockerfile
        restart: on-failure
        env_file: ./.env
        ports:
            - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
        environment:
            SPRING_APPLICATION_JSON: '{
                "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
                "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
                "spring.datasource.url": "jdbc:mysql://mysqldb:$POSTGRESDB_DOCKER_PORT/$POSTGRESDB_DATABASE?allowPublicKeyRetrieval=TRUE",
                "spring.datasource.username": "$POSTGRESDB_USER",
                "spring.datasource.password": "$POSTGRESDB_ROOT_PASSWORD",
                "spring.jpa.show-sql": "true",
                "spring.jpa.hibernate.ddl-auto": "update"
            }'
        stdin_open: true
        tty: true

volumes:
    it_services_pg_data: